rules:
  /:
    /src:
      /**.ts:
        - file
        - camelCaseWithABB
      /*:
        - dir
        - camelCaseWithABB

# 例外，支持中间用*匹配任意字符，**匹配任意路径
exceptions:
  - /.husky
  - /.vscode
  - /example
  - /node_modules
  - /.commitlintrc.json
  - /.dirlintrc.yml
  - /.editorconfig
  - /.eslintignore
  - /.eslintrc.js
  - /.git
  - /.gitignore
  - /.npmignore
  - /.lintstagedrc.json
  - /LICENSE
  - /package-lock.json
  - /package.json
  - /README.md
  - /CHANGELOG.md
  - /tsconfig.json
  - /tsconfig.test.json
  - /decorator
  - /runtime
  - /transformer
  - /types
  - /index.js
  - /index.d.ts
  - /jest.config.ts
  - /.nvmrc
  - /test
  - /coverage
  - /*.tgz
